{% set version = "7.1.1" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 77d9dc5830c4e7ab94f9225bc2f082430399d95c943f1616db41e83a94df38e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - pyface >=6
    - traits
  run:
    - python
    - pyface >=6
    - traits

test:
  imports:
    - traitsui

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
