{% set version = "7.3.0" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 6644b3f8f602a25760702dc8721ba778ce7594504093af14a4869d239e8674f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pyface >=6
    - traits
  run:
    - python >=3.6
    - pyface >=6
    - traits

test:
  imports:
    - traitsui

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
