{% set version = "8.0.0" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.org/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 901b9d1cbc45513e00a7397677b098441b28774b688f30a159bad4801bf40364

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - pyface >=6
    - traits
  run:
    - python >={{ python_min }}
    - pyface >=6
    - traits

test:
  requires:
    - python {{ python_min }}
  imports:
    - traitsui

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
    - larsoner
