{% set version = "6.1.2" %}

package:
  name: traitsui
  version: {{ version }}

source:
  fn: traitsui-{{ version }}.tar.bz2
  url: https://pypi.io/packages/source/t/traitsui/traitsui-{{ version }}.tar.gz
  sha256: 698dd44d6ff6a50502f6ef0ffe545c233f2772e5c37127667302b8c845be9551

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - pyface >=6
    - traits
  run:
    - python
    - pyface >=6
    - traits

test:
  imports:
    - traitsui

about:
  home: http://docs.enthought.com/traitsui/
  license: BSD 3-clause
  summary: TraitsUI - Traits-capable windowing framework

extra:
  recipe-maintainers:
    - grlee77
